version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  hokusai: artsy/hokusai@0.7
  horizon: artsy/release@0.0.1
  yarn: artsy/yarn@6.1.0

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_main: &only_main
  context: hokusai
  filters:
    branches:
      only: main

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  build-deploy:
    jobs:
      - horizon/block:
          <<: *only_release
          context: horizon
          project_id: 266

      - yarn/run:
          name: test-jest
          <<: *not_staging_or_release
          script: "test"

      - cypress/run:
          yarn: true
          start: "yarn dev"
          executor:
            name: cypress/default
            node: 14.19.0

      - hokusai/push:
          name: push-staging-image
          <<: *only_main
          requires:
            - test-jest

      - hokusai/deploy-staging:
          <<: *only_main
          project-name: forque
          requires:
            - push-staging-image

      - hokusai/deploy-production:
          <<: *only_release
          requires:
            - horizon/block
