---
version: '2'
services:
  {{ project_name }}:
    env_file:
      - ../.env.development
      - ../.env.local
    build:
      context: ../
    ports:
      - 3000:3000
    command: ["yarn", "dev"]