import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Hello from "../components/Hello"

const Home: NextPage = () => {
  return (
    <div className="container mx-auto py-6 w-6/12">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <h1 className="text-xxl my-2 font-bold">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="text-xl my-4">
          Get started by editing <code className="">pages/index.js</code>
        </p>

        <div className="">
          <a
            href="https://nextjs.org/docs"
            className="inline-block w-4/12 mr-4 mb-4 p-4 text-left border-2 border-gray-400 rounded-lg"
          >
            <h2 className="text-lg mb-4 font-bold">Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://nextjs.org/learn"
            className="inline-block w-4/12 mr-4 mb-4 p-4 text-left border-2 border-gray-400 rounded-lg"
          >
            <h2 className="text-lg mb-4 font-bold">Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="inline-block w-4/12 mr-4 mb-4 p-4 text-left border-2 border-gray-400 rounded-lg"
          >
            <h2 className="text-lg mb-4 font-bold">Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="inline-block w-4/12 mr-4 mb-4 p-4 text-left border-2 border-gray-400 rounded-lg"
          >
            <h2 className="text-lg mb-4 font-bold">Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="text-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      <Hello />
    </div>
  )
}

export default Home
